name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "dev/**"
      - "docs/**"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "dev/**"
      - "docs/**"
      - ".gitignore"
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |-
          echo "Run tests"
          make submodules
          make image
          docker run --rm -v $(pwd):/code -t cb-mpc bash -c 'make lint && make full-test'
  lib-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |-
          echo "Test on installed library"
          make submodules
          make image
          docker run --rm -v $(pwd):/code -t cb-mpc bash -c 'make build && make install && make benchmark-build && make demos && export CGO_ENABLED=1 && make test-go && make test-go-race'
