name: "Make release"

on:
  push:
    tags:
      - "cb-mpc-*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - name: checkout
      uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2"
      with:
        fetch-depth: 1
        ref: ${{ github.ref_name }}
        path: ${{ github.ref_name }}

    - name: prepare-assets
      run: |
        cd ${{ github.ref_name }}
        bash scripts/make-release.sh ${{ github.ref_name }}

    - name: attestation
      id: attestation
      uses: "actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0"
      with:
        subject-path: ${{ github.ref_name }}/${{ github.ref_name }}.tar.gz

    - name: release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ github.ref_name }} -t "CB-MPC $VERSION" -d --notes " " -R ${{ github.repository }} ${{ github.ref_name }}/${{ github.ref_name }}.tar.gz ${{ steps.attestation.outputs.bundle-path }}
